### ISSUE TITLE
v0.6.0 breaks import and `betanin-shell`

### ISSUE THREAD

**Issue by abdulocracy** [sentriz/betanin#157]
I'm running the Docker image, and changing from `v0.5.6` to `latest` results in imports yielding no MusicBrainz results, even when manually entering ID. The `betanin-shell` is also broken. Downgrading to `v0.5.6` image fixes both issues.

```
[betanin] starting cli program

/downloads/Soichi Terada - 1996 - Sumo Jungle GRANDEUR {Far East Recording ‎– FER-06872} [FLAC] (11 items)

No matching release found for 11 tracks.
For help, see: https://beets.readthedocs.org/en/latest/faq.html#nomatch
➜ [S]kip, Use as-is, as Tracks, Group albums, Enter search, enter Id, aBort,
eDit? 
```

```
xxx@xxx:~/storage/containers/apps$ docker compose exec -it betanin betanin-shell
Traceback (most recent call last):
  File "/usr/bin/betanin-shell", line 4, in <module>
    from betanin.entry.shell import main
  File "/usr/lib/python3.12/site-packages/betanin/entry/shell.py", line 9, in <module>
    from betanin import application
  File "/usr/lib/python3.12/site-packages/betanin/application.py", line 23, in <module>
    from betanin.rest_resources import torrents  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/betanin/rest_resources/torrents.py", line 9, in <module>
    from betanin.jobs import import_torrents
  File "/usr/lib/python3.12/site-packages/betanin/jobs/import_torrents.py", line 17, in <module>
    _spawn_lock = gevent.lock.BoundedSemaphore()
                  ^^^^^^^^^^^
AttributeError: module 'gevent' has no attribute 'lock'
```

**Comment by sentriz** [comment]
shell should be fixed on master. the MB issue is strange, does this happen with any release? or did you test just one?

**Comment by jaguge** [comment]
I have the same problem with imports. It has happened with all imports I made since upgrading.

**Comment by jaguge** [comment]
Still not working in 0.6.3 and now it seems to be also an error with fetchart.
```
[betanin] starting cli program

** error loading plugin fetchart


Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/beetsplug/fetchart.py", line 1445, in _get_sources
    sources = sanitize_pairs(
              ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/beets/util/config.py", line 69, in sanitize_pairs
    raise UnknownPairError(k, v)
beets.util.config.UnknownPairError: setting filesystem itunes amazon albumart coverart=* is not recognized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/beets/plugins.py", line 471, in _get_plugin
    return obj()
           ^^^^^
  File "/usr/lib/python3.12/site-packages/beetsplug/fetchart.py", line 1406, in __init__
    sources = self._get_sources()
              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/beetsplug/fetchart.py", line 1454, in _get_sources
    raise UserError(e)
beets.exceptions.UserError: setting filesystem itunes amazon albumart coverart=* is not recognized

/downloads/Pink Floyd - Wish You Were Here (5 items)


No matching release found for 5 tracks.
For help, see: https://beets.readthedocs.org/en/latest/faq.html#nomatch
```
It still says "No matching release" even if you enter the release ID manually.

**Comment by sentriz** [comment]
ah, that's a beets 2 thing, you need to update beets config to be:

```yaml
fetchart:
  sources:
    - filesystem
    - itunes
    - amazon
    - albumart
    - coverart
```
